services:
  - type: web
    name: model-fine-tuning-labs
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -k uvicorn.workers.UvicornWorker -w 1 --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "3"
      - key: MALLOC_ARENA_MAX
        value: "2"
      - key: CUDA_VISIBLE_DEVICES
        value: "-1"
      - key: TF_FORCE_GPU_ALLOW_GROWTH
        value: "true"
    plan: free