services:
  - type: web
    name: model-fine-tuning-labs
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: >
      gunicorn main:app 
      --workers 1 
      --worker-class uvicorn.workers.UvicornWorker 
      --bind 0.0.0.0:$PORT 
      --timeout 120 
      --keep-alive 5 
      --max-requests 50 
      --max-requests-jitter 5
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "3"
      - key: MALLOC_ARENA_MAX
        value: "2"
      - key: OMP_NUM_THREADS
        value: "1"
      - key: MKL_NUM_THREADS
        value: "1"
      - key: NUMEXPR_NUM_THREADS
        value: "1"
      - key: PYTHONUNBUFFERED
        value: "1"