services:
  - type: web
    name: model-fine-tuning-labs
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1 --limit-max-requests 1000
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      # Memory optimization settings
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "2"
      - key: MALLOC_ARENA_MAX
        value: "2"
      # Disable TensorFlow GPU and optimize memory
      - key: CUDA_VISIBLE_DEVICES
        value: "-1"
      - key: TF_FORCE_GPU_ALLOW_GROWTH
        value: "true"
      - key: TF_KERAS_BACKEND
        value: "tensorflow"