"""initial schema

Revision ID: 71450f6929be
Revises: 
Create Date: 2025-04-01 00:00:32.225077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71450f6929be'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_deployments_id', table_name='deployments')
    op.drop_table('deployments')
    op.alter_column('evaluations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('trainings', 'model_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('trainings', 'dataset_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('trainings', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('trainings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trainings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('trainings', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('trainings', 'dataset_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('trainings', 'model_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('evaluations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.create_table('deployments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('model_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('endpoint_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('metrics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name='deployments_model_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='deployments_owner_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='deployments_pkey')
    )
    op.create_index('ix_deployments_id', 'deployments', ['id'], unique=False)
    # ### end Alembic commands ###
